### PR TITLE
VSCode

### PR DESCRIPTION
**Pull request by leonyu**

### CODE REVIEW

**Comment by madbob** [comment]
Non-free software.
https://code.visualstudio.com/License/

**Comment by leonyu** [comment]
The source code is MIT, you are free to download it and make your own build of it as any OSS product. 

The license you linked is for the binary distributed by them, which contains autoupdate/usage/bug report settings pointed at Microsoft servers. This is the same procedure followed by Java and Chrome.  
https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005

**Comment by ghost** [comment]
@madbob will you reconsider reopening pull request for VSCode? It's a great app, similiar to Atom but way faster and more responsive. I would say it's an awesome application for developers (and this list is about awesome dev tools, right?). It's open source and free, MIT licensed.

If you are not ok with a description @leonyu made in his pull request (mentioning evil MS) you can use my pull request. Or maybe a pull request with a link to the source code, not to (so evil) MS download page, will satisfy you?

Papa bless.

**Comment by ndbeals** [comment]
@leonyu And @edwinjablonski then he'd have to maintain an OSS build of VSCode, I don't think he wants to do that. You're asking him to do a lot of work just to get an editor on a list.

**Comment by leonyu** [comment]
In open source, there are people who are against corporate interest (RMS, GNU, Debian), there are people who tolerate it (Linux, LLVM, Java, etc). Everyone's free to pick their sides. Author appears to be in former camp. 

Since this project is in itself a open source project, if this project was really useful, someone would've forked it for real (not Github fork) and added to it. But this project is just a list of bookmarks, so makes no difference.

**Comment by ghost** [comment]
@ndbeals I think he just don't want to add it because it's a MS product. It's open source, MIT licensed, whole source code is here on github, easy to compile, make patches and so on and on. It's just an open source project like million of others similar projects. Nothing scary.

@leonyu Yeah, the only reason @madbob rejected it it's because it came from MS. 

> But this project is just a list of bookmarks, so makes no difference. 

Yup.

**Comment by ndbeals** [comment]
@edwinjablonski It is not MIT licensed, the source code behind may be, but the compiled release certainly is not. Did you even read the authors first reply? Did you read what the Visual Studio Code License requires?

[https://code.visualstudio.com/License/](https://code.visualstudio.com/License/)

But as you said, it's just a list of bookmarks, don't know why you care so much about getting an editor on "just a list".

**Pull request closed without merging**
